
---

spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: local
    import: "optional:configserver:http://localhost:8888/"

---

spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: stage
    import: "optional:configserver:http://172.17.0.3:8888/"
